### ISSUE TITLE
idea无法显示sql

### ISSUE THREAD

**Issue by dustyou** [pg-liudong/mybatis-log-plus-usage#1]
![image](https://user-images.githubusercontent.com/45392897/163531547-7e1b8041-15c5-4bd0-873a-5df5c3c0dbd2.png)

**Comment by pg-liudong** [comment]
请贴下控制台打印的sql日志

**Comment by rick-2023** [comment]
同遇到该问题，IDEA异常堆栈如下
```
java.lang.RuntimeException: Error while applying com.dong.plugin.filter.MybatisLogConsoleFilter@265796f3 to '==>  Preparing: select * from xxx 
'
   at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:88)
   at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeLine(AsyncFilterRunner.java:231)
   at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeNextLine(AsyncFilterRunner.java:220)
   at com.intellij.execution.impl.AsyncFilterRunner.runTasks(AsyncFilterRunner.java:148)
   at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
   at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
   at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
   at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
   at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
   at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
   at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
   at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
   at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
   at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
   at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
   at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
   at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
   at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
   at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
   at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
   at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
   at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
   at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
   at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
   at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
   at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
   at java.base/java.security.AccessController.doPrivileged(Native Method)
   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
   at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
   at com.dong.plugin.common.util.SqlUtil.collectSqlInfo(SqlUtil.java:287)
   at com.dong.plugin.common.util.SqlUtil.printlnSqlByRowLog(SqlUtil.java:221)
   at com.dong.plugin.filter.MybatisLogConsoleFilter.applyFilter(MybatisLogConsoleFilter.java:30)
   at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:82)
   ... 34 more
```

**Comment by pg-liudong** [comment]
这边是否引入了log4j或者logback等日志文件，并且改变了mybatis原生SQL日志格式呢？如果改了原生SQL日志输出格式，会导致无法解析！

**Comment by pg-liudong** [comment]
解决方案：更改log4j或者logback日志文件，使其保留原生mybatis日志输出格式即可！

**Comment by pg-liudong** [comment]
如果还有问题，欢迎进微信群交流，平日较忙，回复不及时，还请见谅！
